services:
  telegram-bot:
    build: .
    volumes:
      - ./bot:/app/bot
      - ./bot/reminders.db:/app/bot/reminders.db  # persist the DB file
      - ./bot/bot.log:/app/bot/bot.log            # persist log file
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Singapore
    restart: unless-stopped

volumes:
  db-data:
