services:
  telegram-bot:
    build: .
    volumes:
      - ./bot:/app/bot
      - ./bot/bot.log:/app/bot/bot.log            # persist log file
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Singapore
      - ENV=prod
    working_dir: /app
    networks:
      - wen-network
    restart: unless-stopped

  telegram-bot-dev:
    build: .
    volumes:
      - ./bot:/app/bot
      - ./bot/bot.log:/app/bot/bot.log            # persist log file
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Singapore
      - ENV=dev
    working_dir: /app
    networks:
      - wen-network

volumes:
  db-data:

networks:
  wen-network:
    external: true