services:
  reminder-bot-prod:
    build: .
    container_name: reminder_bot_prod
    image: reminder_bot:bot-prod
    volumes:
      - ./bot:/app/bot
      - ./bot/bot.log:/app/bot/bot.log            # persist log file
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Singapore
      - ENV=prod
    working_dir: /app
    networks:
      - wen-network
    restart: unless-stopped

  reminder-bot-dev:
    build: .
    image: reminder_bot:bot-dev
    container_name: reminder_bot_dev
    volumes:
      - ./bot:/app/bot
      - ./bot/bot.log:/app/bot/bot.log            # persist log file
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Singapore
      - ENV=dev
    working_dir: /app
    networks:
      - wen-network

volumes:
  db-data:

networks:
  wen-network:
    external: true